//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabularEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabularEditor.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a {0} to a Power BI Data Model is not allowed..
        /// </summary>
        internal static string CannotCreatePowerBIObject {
            get {
                return ResourceManager.GetString("CannotCreatePowerBIObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Table Columns cannot be deleted. Hide the column or revisit the Calculated Table expression instead..
        /// </summary>
        internal static string CannotDeleteCalculatedTableColumn {
            get {
                return ResourceManager.GetString("CannotDeleteCalculatedTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object cannot be deleted..
        /// </summary>
        internal static string CannotDeleteObject {
            get {
                return ResourceManager.GetString("CannotDeleteObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a {0} from a Power BI Data Model is not allowed..
        /// </summary>
        internal static string CannotDeletePowerBIObject {
            get {
                return ResourceManager.GetString("CannotDeletePowerBIObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column is used in one or more hierarchies. The corresponding levels will also be deleted..
        /// </summary>
        internal static string ColumnUsedInHierarchy {
            get {
                return ResourceManager.GetString("ColumnUsedInHierarchy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column is used in one or more relationships. Deleting it will also remove the relationship from the model..
        /// </summary>
        internal static string ColumnUsedInRelationship {
            get {
                return ResourceManager.GetString("ColumnUsedInRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Level Security requires Compatibility Level 1400 or higher..
        /// </summary>
        internal static string CompatibilityError_ObjectLevelSecurity {
            get {
                return ResourceManager.GetString("CompatibilityError_ObjectLevelSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structured Data Sources can only be added to Compatibility Level 1400 or higher models..
        /// </summary>
        internal static string CompatibilityError_StructuredDataSource {
            get {
                return ResourceManager.GetString("CompatibilityError_StructuredDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data source which is used by one or more partitions cannot be deleted..
        /// </summary>
        internal static string DataSourceInUse {
            get {
                return ResourceManager.GetString("DataSourceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A column with the name &quot;{0}&quot; already exists in the table. Choose a different name for this column..
        /// </summary>
        internal static string DuplicateColumnName {
            get {
                return ResourceManager.GetString("DuplicateColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A measure with the name &quot;{0}&quot; already exists in the model. Choose a different name for this measure..
        /// </summary>
        internal static string DuplicateMeasureName {
            get {
                return ResourceManager.GetString("DuplicateMeasureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} object does not have a DAX {1} property..
        /// </summary>
        internal static string InvalidExpressionProperty {
            get {
                return ResourceManager.GetString("InvalidExpressionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove this object from the TOM since it has already been deleted..
        /// </summary>
        internal static string ObjectAlreadyDeleted {
            get {
                return ResourceManager.GetString("ObjectAlreadyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string OperationDelete {
            get {
                return ResourceManager.GetString("OperationDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be blank..
        /// </summary>
        internal static string ParameterBlankNotAllowed {
            get {
                return ResourceManager.GetString("ParameterBlankNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This object is referenced by one or more other objects through DAX expressions. Deleting it will cause dependent objects to stop functioning correctly..
        /// </summary>
        internal static string ReferencedByDAX {
            get {
                return ResourceManager.GetString("ReferencedByDAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A table must have at least one partition..
        /// </summary>
        internal static string TableMustHaveAtLeastOnePartition {
            get {
                return ResourceManager.GetString("TableMustHaveAtLeastOnePartition", resourceCulture);
            }
        }
    }
}
