// Code generated by a template
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel;
using TabularEditor.PropertyGridUI;
using TabularEditor.UndoFramework;
using TOM = Microsoft.AnalysisServices.Tabular;

namespace TabularEditor.TOMWrapper
{
  
    /// <summary>
	/// Base class declaration for CalculatedTableColumn
	/// </summary>
	[TypeConverter(typeof(DynamicPropertyConverter))]
	public partial class CalculatedTableColumn: Column
	{
	    protected internal new TOM.CalculatedTableColumn MetadataObject { get { return base.MetadataObject as TOM.CalculatedTableColumn; } internal set { base.MetadataObject = value; } }

        /// <summary>
        /// Gets or sets the IsNameInferred of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Name Inferred")]
		[Category("Other"),IntelliSense("The Name Inferred of this CalculatedTableColumn.")]
		public bool IsNameInferred {
			get {
			    return MetadataObject.IsNameInferred;
			}
			set {
				var oldValue = IsNameInferred;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("IsNameInferred", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.IsNameInferred = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "IsNameInferred", oldValue, value));
				OnPropertyChanged("IsNameInferred", oldValue, value);
			}
		}
		private bool ShouldSerializeIsNameInferred() { return false; }
        /// <summary>
        /// Gets or sets the IsDataTypeInferred of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Data Type Inferred")]
		[Category("Other"),IntelliSense("The Data Type Inferred of this CalculatedTableColumn.")]
		public bool IsDataTypeInferred {
			get {
			    return MetadataObject.IsDataTypeInferred;
			}
			set {
				var oldValue = IsDataTypeInferred;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("IsDataTypeInferred", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.IsDataTypeInferred = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "IsDataTypeInferred", oldValue, value));
				OnPropertyChanged("IsDataTypeInferred", oldValue, value);
			}
		}
		private bool ShouldSerializeIsDataTypeInferred() { return false; }
        /// <summary>
        /// Gets or sets the SourceColumn of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Source Column")]
		[Category("Options"),IntelliSense("The Source Column of this CalculatedTableColumn.")]
		public string SourceColumn {
			get {
			    return MetadataObject.SourceColumn;
			}
			set {
				var oldValue = SourceColumn;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("SourceColumn", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.SourceColumn = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "SourceColumn", oldValue, value));
				OnPropertyChanged("SourceColumn", oldValue, value);
			}
		}
		private bool ShouldSerializeSourceColumn() { return false; }
        /// <summary>
        /// Gets or sets the ColumnOrigin of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Column Origin")]
		[Category("Other"),IntelliSense("The Column Origin of this CalculatedTableColumn.")]
		public Column ColumnOrigin {
			get {
				if (MetadataObject.ColumnOrigin == null) return null;
			    return Handler.WrapperLookup[MetadataObject.ColumnOrigin] as Column;
            }
			
		}
		private bool ShouldSerializeColumnOrigin() { return false; }



		/// <summary>
		/// Creates a new CalculatedTableColumn and adds it to the parent Table.
		/// </summary>
		public CalculatedTableColumn(Table parent) : base(new TOM.CalculatedTableColumn()) {
			MetadataObject.Name = parent.MetadataObject.Columns.GetNewName("New CalculatedTableColumn");
			parent.Columns.Add(this);
			Init();
		}
	
        internal override void RenewMetadataObject()
        {
            var tom = new TOM.CalculatedTableColumn();
            Handler.WrapperLookup.Remove(MetadataObject);
            MetadataObject.CopyTo(tom);
            MetadataObject = tom;
            Handler.WrapperLookup.Add(MetadataObject, this);
        }


		public Table Parent { 
			get {
				return Handler.WrapperLookup[MetadataObject.Parent] as Table;
			}
		}

		public CalculatedTableColumn Clone(string newName = null) {
		    Handler.BeginUpdate("Clone CalculatedTableColumn");

				var tom = MetadataObject.Clone();
				tom.Name = Parent.Columns.MetadataObjectCollection.GetNewName(string.IsNullOrEmpty(newName) ? tom.Name + " copy" : newName);
				var obj = new CalculatedTableColumn(tom);

            Handler.EndUpdate();

            return obj;
		}

		
		/// <summary>
		/// Creates a CalculatedTableColumn object representing an existing TOM CalculatedTableColumn.
		/// </summary>
		internal CalculatedTableColumn(TOM.CalculatedTableColumn metadataObject) : base(metadataObject)
		{
		}	
    }
}
