// Code generated by a template
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel;
using TabularEditor.PropertyGridUI;
using TabularEditor.UndoFramework;
using TOM = Microsoft.AnalysisServices.Tabular;

namespace TabularEditor.TOMWrapper
{
  
    /// <summary>
	/// Base class declaration for CalculatedTableColumn
	/// </summary>
	[TypeConverter(typeof(DynamicPropertyConverter))]
	public partial class CalculatedTableColumn: Column
			, IClonableObject
	{
	    protected internal new TOM.CalculatedTableColumn MetadataObject { get { return base.MetadataObject as TOM.CalculatedTableColumn; } internal set { base.MetadataObject = value; } }

        /// <summary>
        /// Gets or sets the IsNameInferred of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Name Inferred")]
		[Category("Other"),IntelliSense("The Name Inferred of this CalculatedTableColumn.")]
		public bool IsNameInferred {
			get {
			    return MetadataObject.IsNameInferred;
			}
			set {
				var oldValue = IsNameInferred;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("IsNameInferred", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.IsNameInferred = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "IsNameInferred", oldValue, value));
				OnPropertyChanged("IsNameInferred", oldValue, value);
			}
		}
		private bool ShouldSerializeIsNameInferred() { return false; }
        /// <summary>
        /// Gets or sets the IsDataTypeInferred of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Data Type Inferred")]
		[Category("Other"),IntelliSense("The Data Type Inferred of this CalculatedTableColumn.")]
		public bool IsDataTypeInferred {
			get {
			    return MetadataObject.IsDataTypeInferred;
			}
			set {
				var oldValue = IsDataTypeInferred;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("IsDataTypeInferred", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.IsDataTypeInferred = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "IsDataTypeInferred", oldValue, value));
				OnPropertyChanged("IsDataTypeInferred", oldValue, value);
			}
		}
		private bool ShouldSerializeIsDataTypeInferred() { return false; }
        /// <summary>
        /// Gets or sets the SourceColumn of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Source Column")]
		[Category("Options"),IntelliSense("The Source Column of this CalculatedTableColumn.")]
		public string SourceColumn {
			get {
			    return MetadataObject.SourceColumn;
			}
			set {
				var oldValue = SourceColumn;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("SourceColumn", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.SourceColumn = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "SourceColumn", oldValue, value));
				OnPropertyChanged("SourceColumn", oldValue, value);
			}
		}
		private bool ShouldSerializeSourceColumn() { return false; }
        /// <summary>
        /// Gets or sets the ColumnOrigin of the CalculatedTableColumn.
        /// </summary>
		[DisplayName("Column Origin")]
		[Category("Other"),IntelliSense("The Column Origin of this CalculatedTableColumn.")]
		public Column ColumnOrigin {
			get {
				if (MetadataObject.ColumnOrigin == null) return null;
			    return Handler.WrapperLookup[MetadataObject.ColumnOrigin] as Column;
            }
			
		}
		private bool ShouldSerializeColumnOrigin() { return false; }



		/// <summary>
		/// Creates a new CalculatedTableColumn and adds it to the parent Table.
		/// Also creates the underlying metadataobject and adds it to the TOM tree.
		/// </summary>
		public CalculatedTableColumn(Table parent, string name = null) : this(new TOM.CalculatedTableColumn()) {
			
			MetadataObject.Name = GetNewName(parent.MetadataObject.Columns, string.IsNullOrWhiteSpace(name) ? "New CalculatedTableColumn" : name);

			parent.Columns.Add(this);
		}


		/// <summary>
		/// Creates an exact copy of this CalculatedTableColumn object.
		/// </summary>
		public CalculatedTableColumn Clone(string newName = null, bool includeTranslations = true, Table newParent = null) {
		    Handler.BeginUpdate("Clone CalculatedTableColumn");

				// Create a clone of the underlying metadataobject:
				var tom = MetadataObject.Clone() as TOM.CalculatedTableColumn;

				// Assign a new, unique name:
				tom.Name = Parent.Columns.MetadataObjectCollection.GetNewName(string.IsNullOrEmpty(newName) ? tom.Name + " copy" : newName);
				
				// Create the TOM Wrapper object, representing the metadataobject:
				var obj = new CalculatedTableColumn(tom);

				// Add the object to the parent collection:
				if(newParent != null) 
					newParent.Columns.Add(obj);
				else
    				Parent.Columns.Add(obj);

				// Copy translations, if applicable:
				if(includeTranslations) {
					obj.TranslatedNames.CopyFrom(TranslatedNames);
					obj.TranslatedDescriptions.CopyFrom(TranslatedDescriptions);
					obj.TranslatedDisplayFolders.CopyFrom(TranslatedDisplayFolders);
				}
				
				// Copy perspectives:
				obj.InPerspective.CopyFrom(InPerspective);


            Handler.EndUpdate();

            return obj;
		}

		TabularNamedObject IClonableObject.Clone(string newName, bool includeTranslations, TabularNamedObject newParent) 
		{
			return Clone(newName);
		}

	
        internal override void RenewMetadataObject()
        {
            var tom = new TOM.CalculatedTableColumn();
            Handler.WrapperLookup.Remove(MetadataObject);
            MetadataObject.CopyTo(tom);
            MetadataObject = tom;
            Handler.WrapperLookup.Add(MetadataObject, this);
        }


		public Table Parent { 
			get {
				return Handler.WrapperLookup[MetadataObject.Parent] as Table;
			}
		}

		/// <summary>
		/// Creates a CalculatedTableColumn object representing an existing TOM CalculatedTableColumn.
		/// </summary>
		internal CalculatedTableColumn(TOM.CalculatedTableColumn metadataObject) : base(metadataObject)
		{
		}	

		public override bool Browsable(string propertyName) {
			switch (propertyName) {
				case "Parent":
					return false;
				
				default:
					return base.Browsable(propertyName);
			}
		}

    }

}
