// Code generated by a template
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel;
using TabularEditor.PropertyGridUI;
using TabularEditor.UndoFramework;
using TOM = Microsoft.AnalysisServices.Tabular;

namespace TabularEditor.TOMWrapper
{
  
    /// <summary>
	/// Base class declaration for CalculatedColumn
	/// </summary>
	[TypeConverter(typeof(DynamicPropertyConverter))]
	public partial class CalculatedColumn: Column
			, IExpressionObject
			, IClonableObject
	{
	    protected internal new TOM.CalculatedColumn MetadataObject { get { return base.MetadataObject as TOM.CalculatedColumn; } internal set { base.MetadataObject = value; } }

        /// <summary>
        /// Gets or sets the IsDataTypeInferred of the CalculatedColumn.
        /// </summary>
		[DisplayName("Data Type Inferred")]
		[Category("Other"),IntelliSense("The Data Type Inferred of this CalculatedColumn.")]
		public bool IsDataTypeInferred {
			get {
			    return MetadataObject.IsDataTypeInferred;
			}
			set {
				var oldValue = IsDataTypeInferred;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("IsDataTypeInferred", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.IsDataTypeInferred = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "IsDataTypeInferred", oldValue, value));
				OnPropertyChanged("IsDataTypeInferred", oldValue, value);
			}
		}
		private bool ShouldSerializeIsDataTypeInferred() { return false; }
        /// <summary>
        /// Gets or sets the Expression of the CalculatedColumn.
        /// </summary>
		[DisplayName("Expression")]
		[Category("Options"),IntelliSense("The Expression of this CalculatedColumn.")][Editor(typeof(System.ComponentModel.Design.MultilineStringEditor), typeof(System.Drawing.Design.UITypeEditor))]
		public string Expression {
			get {
			    return MetadataObject.Expression;
			}
			set {
				var oldValue = Expression;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("Expression", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.Expression = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "Expression", oldValue, value));
				OnPropertyChanged("Expression", oldValue, value);
			}
		}
		private bool ShouldSerializeExpression() { return false; }



		/// <summary>
		/// Creates a new CalculatedColumn and adds it to the parent Table.
		/// </summary>
		public CalculatedColumn(Table parent, string name = null) : this(new TOM.CalculatedColumn()) {
			
			MetadataObject.Name = GetNewName(parent.MetadataObject.Columns, string.IsNullOrWhiteSpace(name) ? "New CalculatedColumn" : name);

			parent.Columns.Add(this);
		}


		/// <summary>
		/// Creates an exact copy of this CalculatedColumn object.
		/// </summary>
		/// 
		public CalculatedColumn Clone(string newName = null, bool includeTranslations = true, Table newParent = null) {
		    Handler.BeginUpdate("Clone CalculatedColumn");

				// Create a clone of the underlying metadataobject:
				var tom = MetadataObject.Clone() as TOM.CalculatedColumn;

				// Assign a new, unique name:
				tom.Name = Parent.Columns.MetadataObjectCollection.GetNewName(string.IsNullOrEmpty(newName) ? tom.Name + " copy" : newName);
				
				// Create the TOM Wrapper object, representing the metadataobject:
				var obj = new CalculatedColumn(tom);

				// Add the object to the parent collection:
				if(newParent != null) 
					newParent.Columns.Add(obj);
				else
    				Parent.Columns.Add(obj);

				// Copy translations, if applicable:
				if(includeTranslations) {
					obj.TranslatedNames.CopyFrom(TranslatedNames);
					obj.TranslatedDescriptions.CopyFrom(TranslatedDescriptions);
					obj.TranslatedDisplayFolders.CopyFrom(TranslatedDisplayFolders);
				}
				
				// Copy perspectives:
				obj.InPerspective.CopyFrom(InPerspective);


            Handler.EndUpdate();

            return obj;
		}

		TabularNamedObject IClonableObject.Clone(string newName, bool includeTranslations, TabularNamedObject newParent) 
		{
			return Clone(newName);
		}

	
        internal override void RenewMetadataObject()
        {
            var tom = new TOM.CalculatedColumn();
            Handler.WrapperLookup.Remove(MetadataObject);
            MetadataObject.CopyTo(tom);
            MetadataObject = tom;
            Handler.WrapperLookup.Add(MetadataObject, this);
        }


		public Table Parent { 
			get {
				return Handler.WrapperLookup[MetadataObject.Parent] as Table;
			}
		}

		/// <summary>
		/// Creates a CalculatedColumn object representing an existing TOM CalculatedColumn.
		/// </summary>
		internal CalculatedColumn(TOM.CalculatedColumn metadataObject) : base(metadataObject)
		{
		}	

		public override bool Browsable(string propertyName) {
			switch (propertyName) {
				case "Parent":
					return false;
				
				default:
					return base.Browsable(propertyName);
			}
		}

    }

}
