// Code generated by a template
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel;
using TabularEditor.PropertyGridUI;
using TabularEditor.UndoFramework;
using TOM = Microsoft.AnalysisServices.Tabular;

namespace TabularEditor.TOMWrapper
{
  
    /// <summary>
	/// Base class declaration for DataColumn
	/// </summary>
	[TypeConverter(typeof(DynamicPropertyConverter))]
	public partial class DataColumn: Column, IClonableObject
	{
	    protected internal new TOM.DataColumn MetadataObject { get { return base.MetadataObject as TOM.DataColumn; } internal set { base.MetadataObject = value; } }

        /// <summary>
        /// Gets or sets the SourceColumn of the DataColumn.
        /// </summary>
		[DisplayName("Source Column")]
		[Category("Options"),IntelliSense("The Source Column of this DataColumn.")]
		public string SourceColumn {
			get {
			    return MetadataObject.SourceColumn;
			}
			set {
				var oldValue = SourceColumn;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("SourceColumn", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.SourceColumn = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "SourceColumn", oldValue, value));
				OnPropertyChanged("SourceColumn", oldValue, value);
			}
		}
		private bool ShouldSerializeSourceColumn() { return false; }



		/// <summary>
		/// Creates a new DataColumn and adds it to the parent Table.
		/// </summary>
		public DataColumn(Table parent) : this(new TOM.DataColumn()) {
			MetadataObject.Name = parent.MetadataObject.Columns.GetNewName("New DataColumn");
			parent.Columns.Add(this);
		}


		public DataColumn Clone(string newName = null) {
		    Handler.BeginUpdate("Clone DataColumn");

				var tom = MetadataObject.Clone() as TOM.DataColumn;
				tom.Name = Parent.Columns.MetadataObjectCollection.GetNewName(string.IsNullOrEmpty(newName) ? tom.Name + " copy" : newName);
				var obj = new DataColumn(tom);

            Handler.EndUpdate();

            return obj;
		}

		TabularNamedObject IClonableObject.Clone(string newName, bool includeTranslations) {
			if (includeTranslations) throw new ArgumentException("This object does not support translations.", "includeTranslations");
			return Clone(newName);
		}

	
        internal override void RenewMetadataObject()
        {
            var tom = new TOM.DataColumn();
            Handler.WrapperLookup.Remove(MetadataObject);
            MetadataObject.CopyTo(tom);
            MetadataObject = tom;
            Handler.WrapperLookup.Add(MetadataObject, this);
        }


		public Table Parent { 
			get {
				return Handler.WrapperLookup[MetadataObject.Parent] as Table;
			}
		}
		
		/// <summary>
		/// Creates a DataColumn object representing an existing TOM DataColumn.
		/// </summary>
		internal DataColumn(TOM.DataColumn metadataObject) : base(metadataObject)
		{
			
		}	
    }
}
