// Code generated by a template
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel;
using TabularEditor.PropertyGridUI;
using TabularEditor.UndoFramework;
using TOM = Microsoft.AnalysisServices.Tabular;

namespace TabularEditor.TOMWrapper
{
  
    /// <summary>
	/// Base class declaration for Perspective
	/// </summary>
	[TypeConverter(typeof(DynamicPropertyConverter))]
	public partial class Perspective: TabularNamedObject
			, IDescriptionObject
			, IAnnotationObject
			, ITranslatableObject
			, IClonableObject
	{
	    protected internal new TOM.Perspective MetadataObject { get { return base.MetadataObject as TOM.Perspective; } internal set { base.MetadataObject = value; } }

		public string GetAnnotation(string name) {
		    return MetadataObject.Annotations.Find(name)?.Value;
		}
		public void SetAnnotation(string name, string value, bool undoable = true) {
			if(MetadataObject.Annotations.Contains(name)) {
				MetadataObject.Annotations[name].Value = value;
			} else {
				MetadataObject.Annotations.Add(new TOM.Annotation{ Name = name, Value = value });
			}
			if (undoable) Handler.UndoManager.Add(new UndoAnnotationAction(this, name, value));
		}
		        /// <summary>
        /// Gets or sets the Description of the Perspective.
        /// </summary>
		[DisplayName("Description")]
		[Category("Basic"),IntelliSense("The Description of this Perspective.")]
		public string Description {
			get {
			    return MetadataObject.Description;
			}
			set {
				var oldValue = Description;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging("Description", value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.Description = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, "Description", oldValue, value));
				OnPropertyChanged("Description", oldValue, value);
			}
		}
		private bool ShouldSerializeDescription() { return false; }

        /// <summary>
        /// Collection of localized descriptions for this Perspective.
        /// </summary>
        [Browsable(true),DisplayName("Descriptions"),Category("Translations and Perspectives")]
	    public TranslationIndexer TranslatedDescriptions { private set; get; }
        /// <summary>
        /// Collection of localized names for this Perspective.
        /// </summary>
        [Browsable(true),DisplayName("Names"),Category("Translations and Perspectives")]
	    public TranslationIndexer TranslatedNames { private set; get; }



		/// <summary>
		/// Creates a new Perspective and adds it to the parent Model.
		/// </summary>
		public Perspective(Model parent, string name = null) : this(new TOM.Perspective()) {
			
			MetadataObject.Name = GetNewName(parent.MetadataObject.Perspectives, string.IsNullOrWhiteSpace(name) ? "New Perspective" : name);

			parent.Perspectives.Add(this);
		}

		
		public Perspective() : this(TabularModelHandler.Singleton.Model) { }


		/// <summary>
		/// Creates an exact copy of this Perspective object.
		/// </summary>
		/// 
		public Perspective Clone(string newName = null, bool includeTranslations = true) {
		    Handler.BeginUpdate("Clone Perspective");

				// Create a clone of the underlying metadataobject:
				var tom = MetadataObject.Clone() as TOM.Perspective;

				// Assign a new, unique name:
				tom.Name = Parent.Perspectives.MetadataObjectCollection.GetNewName(string.IsNullOrEmpty(newName) ? tom.Name + " copy" : newName);
				
				// Create the TOM Wrapper object, representing the metadataobject:
				var obj = new Perspective(tom);

				// Add the object to the parent collection:
				Parent.Perspectives.Add(obj);

				// Copy translations, if applicable:
				if(includeTranslations) {
					obj.TranslatedNames.CopyFrom(TranslatedNames);
					obj.TranslatedDescriptions.CopyFrom(TranslatedDescriptions);
				}


            Handler.EndUpdate();

            return obj;
		}

		TabularNamedObject IClonableObject.Clone(string newName, bool includeTranslations, TabularNamedObject newParent) 
		{
			if (newParent != null) throw new ArgumentException("This object can not be cloned to another parent. Argument newParent should be left as null.", "newParent");
			return Clone(newName, includeTranslations);
		}

	
        internal override void RenewMetadataObject()
        {
            var tom = new TOM.Perspective();
            Handler.WrapperLookup.Remove(MetadataObject);
            MetadataObject.CopyTo(tom);
            MetadataObject = tom;
            Handler.WrapperLookup.Add(MetadataObject, this);
        }


		public Model Parent { 
			get {
				return Handler.WrapperLookup[MetadataObject.Parent] as Model;
			}
		}

		/// <summary>
		/// Creates a Perspective object representing an existing TOM Perspective.
		/// </summary>
		internal Perspective(TOM.Perspective metadataObject) : base(metadataObject)
		{
			TranslatedNames = new TranslationIndexer(this, TOM.TranslatedProperty.Caption);
			TranslatedDescriptions = new TranslationIndexer(this, TOM.TranslatedProperty.Description);
		}	

		public override bool Browsable(string propertyName) {
			switch (propertyName) {
				case "Parent":
					return false;
				
				// Hides translation properties in the grid, unless the model actually contains translations:
				case "TranslatedNames":
				case "TranslatedDescriptions":
					return Model.Cultures.Any();
				
				default:
					return base.Browsable(propertyName);
			}
		}

    }


	/// <summary>
	/// Collection class for Perspective. Provides convenient properties for setting a property on multiple objects at once.
	/// </summary>
	public partial class PerspectiveCollection: TabularObjectCollection<Perspective, TOM.Perspective, TOM.Model>
	{
		public Model Parent { get; private set; }

		public PerspectiveCollection(string collectionName, TOM.PerspectiveCollection metadataObjectCollection, Model parent) : base(collectionName, metadataObjectCollection)
		{
			Parent = parent;

			// Construct child objects (they are automatically added to the Handler's WrapperLookup dictionary):
			foreach(var obj in MetadataObjectCollection) {
				new Perspective(obj) { Collection = this };
			}
		}

		[Description("Sets the Description property of all objects in the collection at once.")]
		public string Description {
			set {
				if(Handler == null) return;
				Handler.UndoManager.BeginBatch(UndoPropertyChangedAction.GetActionNameFromProperty("Description"));
				this.ToList().ForEach(item => { item.Description = value; });
				Handler.UndoManager.EndBatch();
			}
		}

		public override string ToString() {
			return string.Format("({0} {1})", Count, (Count == 1 ? "Perspective" : "Perspectives").ToLower());
		}
	}
}
