
// Code generated by a template
using System;
using System.Linq;
using System.Collections.Generic;
using System.ComponentModel;
using TabularEditor.PropertyGridUI;
using TabularEditor.UndoFramework;
using System.Drawing.Design;
using TOM = Microsoft.AnalysisServices.Tabular;
namespace TabularEditor.TOMWrapper
{
  
	
	[TypeConverter(typeof(DynamicPropertyConverter))]
	public partial class StructuredDataSource: DataSource
			, IClonableObject
	{
	    protected internal new TOM.StructuredDataSource MetadataObject { get { return base.MetadataObject as TOM.StructuredDataSource; } internal set { base.MetadataObject = value; } }


		[DisplayName("Context Expression")]
		[Category("Other"),Description(@""),IntelliSense("The Context Expression of this StructuredDataSource.")][Editor(typeof(System.ComponentModel.Design.MultilineStringEditor), typeof(System.Drawing.Design.UITypeEditor))]
		public string ContextExpression {
			get {
			    return MetadataObject.ContextExpression;
			}
			set {
				var oldValue = ContextExpression;
				if (oldValue == value) return;
				bool undoable = true;
				bool cancel = false;
				OnPropertyChanging(Properties.CONTEXTEXPRESSION, value, ref undoable, ref cancel);
				if (cancel) return;
				MetadataObject.ContextExpression = value;
				if(undoable) Handler.UndoManager.Add(new UndoPropertyChangedAction(this, Properties.CONTEXTEXPRESSION, oldValue, value));
				OnPropertyChanged(Properties.CONTEXTEXPRESSION, oldValue, value);
			}
		}
		private bool ShouldSerializeContextExpression() { return false; }


		public static StructuredDataSource CreateFromMetadata(TOM.StructuredDataSource metadataObject, bool init = true) {
			var obj = new StructuredDataSource(metadataObject, init);
			if(init) 
			{
				obj.InternalInit();
				obj.Init();
			}
			return obj;
		}


		/// <summary>
		/// Creates a new StructuredDataSource and adds it to the parent Model.
		/// Also creates the underlying metadataobject and adds it to the TOM tree.
		/// </summary>
		public static StructuredDataSource CreateNew(Model parent, string name = null)
		{
			var metadataObject = new TOM.StructuredDataSource();
			metadataObject.Name = parent.DataSources.GetNewName(string.IsNullOrWhiteSpace(name) ? "New StructuredDataSource" : name);

			var obj = new StructuredDataSource(metadataObject);

			parent.DataSources.Add(obj);
			
			obj.Init();

			return obj;
		}

		/// <summary>
		/// Creates a new StructuredDataSource and adds it to the current Model.
		/// Also creates the underlying metadataobject and adds it to the TOM tree.
		/// </summary>		
		public static StructuredDataSource CreateNew(string name = null)
		{
			var metadataObject = new TOM.StructuredDataSource();
			metadataObject.Name = TabularModelHandler.Singleton.Model.DataSources.GetNewName(string.IsNullOrWhiteSpace(name) ? "New StructuredDataSource" : name);

			var obj = new StructuredDataSource(metadataObject);

			TabularModelHandler.Singleton.Model.DataSources.Add(obj);

			obj.Init();

			return obj;
		}


		/// <summary>
		/// Creates an exact copy of this StructuredDataSource object.
		/// </summary>
		public StructuredDataSource Clone(string newName = null) {
		    Handler.BeginUpdate("Clone StructuredDataSource");

			// Create a clone of the underlying metadataobject:
			var tom = MetadataObject.Clone() as TOM.StructuredDataSource;


			// Assign a new, unique name:
			tom.Name = Parent.DataSources.GetNewName(string.IsNullOrEmpty(newName) ? tom.Name + " copy" : newName);
				
			// Create the TOM Wrapper object, representing the metadataobject (but don't init until after we add it to the parent):
			var obj = CreateFromMetadata(tom, false);

			// Add the object to the parent collection:
			Parent.DataSources.Add(obj);

			obj.InternalInit();
			obj.Init();


            Handler.EndUpdate();

            return obj;
		}

		TabularNamedObject IClonableObject.Clone(string newName, bool includeTranslations, TabularNamedObject newParent) 
		{
			if (includeTranslations) throw new ArgumentException("This object does not support translations", "includeTranslations");
			if (newParent != null) throw new ArgumentException("This object can not be cloned to another parent. Argument newParent should be left as null.", "newParent");
			return Clone(newName);
		}

	
        internal override void RenewMetadataObject()
        {
            Handler.WrapperLookup.Remove(MetadataObject);
            MetadataObject = MetadataObject.Clone() as TOM.StructuredDataSource;
            Handler.WrapperLookup.Add(MetadataObject, this);
        }

		public Model Parent { 
			get {
				return Handler.WrapperLookup[MetadataObject.Parent] as Model;
			}
		}



		/// <summary>
		/// CTOR - only called from static factory methods on the class
		/// </summary>
		protected StructuredDataSource(TOM.StructuredDataSource metadataObject, bool init = true) : base(metadataObject)
		{
			if(init) InternalInit();
		}

		private void InternalInit()
		{
		}



		internal override void Undelete(ITabularObjectCollection collection) {
			base.Undelete(collection);
			Reinit();
			ReapplyReferences();
		}

		public override bool Browsable(string propertyName) {
			switch (propertyName) {
				case Properties.PARENT:
					return false;
				
				default:
					return base.Browsable(propertyName);
			}
		}

    }

}
