//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabularEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TabularEditor.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose folder for build output.
        /// </summary>
        internal static string ExportBuildChooseFolderCaption {
            get {
                return ResourceManager.GetString("ExportBuildChooseFolderCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ConfigurationSettings xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ddl2=&quot;http://schemas.microsoft.com/analysisservices/2003/engine/2&quot; xmlns:ddl2_2=&quot;http://schemas.microsoft.com/analysisservices/2003/engine/2/2&quot; xmlns:ddl100_100=&quot;http://schemas.microsoft.com/analysisservices/2008/engine/100/100&quot; xmlns:ddl200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/200&quot; xmlns:ddl200_200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportBuildConfig {
            get {
                return ResourceManager.GetString("ExportBuildConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DataSource&gt;
        ///        &lt;ID&gt;{0}&lt;/ID&gt;
        ///        &lt;ConnectionString&gt;{1}&lt;/ConnectionString&gt;
        ///        &lt;ManagedProvider&gt;&lt;/ManagedProvider&gt;
        ///        &lt;ImpersonationInfo&gt;
        ///          &lt;ImpersonationMode xmlns=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;&gt;{2}&lt;/ImpersonationMode&gt;
        ///          &lt;Account xmlns=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;&gt;{3}&lt;/Account&gt;
        ///          &lt;Password xmlns=&quot;http://schemas.microsoft.com/analysisservices/2003/engine&quot;&gt;{4}&lt;/Password&gt;
        ///          &lt;ImpersonationInfoSe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportBuildConfigDataSource {
            get {
                return ResourceManager.GetString("ExportBuildConfigDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This folder already contains one or more build files. Do you want to overwrite these files?.
        /// </summary>
        internal static string ExportBuildConfirmOverwrite {
            get {
                return ResourceManager.GetString("ExportBuildConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing build?.
        /// </summary>
        internal static string ExportBuildConfirmOverwriteCaption {
            get {
                return ResourceManager.GetString("ExportBuildConfirmOverwriteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentOptions xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ddl2=&quot;http://schemas.microsoft.com/analysisservices/2003/engine/2&quot; xmlns:ddl2_2=&quot;http://schemas.microsoft.com/analysisservices/2003/engine/2/2&quot; xmlns:ddl100_100=&quot;http://schemas.microsoft.com/analysisservices/2008/engine/100/100&quot; xmlns:ddl200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/200&quot; xmlns:ddl200_200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/200/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportBuildDeploymentOptions {
            get {
                return ResourceManager.GetString("ExportBuildDeploymentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentTarget xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:ddl2=&quot;http://schemas.microsoft.com/analysisservices/2003/engine/2&quot; xmlns:ddl2_2=&quot;http://schemas.microsoft.com/analysisservices/2003/engine/2/2&quot; xmlns:ddl100_100=&quot;http://schemas.microsoft.com/analysisservices/2008/engine/100/100&quot; xmlns:ddl200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/200&quot; xmlns:ddl200_200=&quot;http://schemas.microsoft.com/analysisservices/2010/engine/200/200 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportBuildDeploymentTargets {
            get {
                return ResourceManager.GetString("ExportBuildDeploymentTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build files successfully exported:
        ///
        ///{0}
        ///
        ///Make sure to check the settings in the files before executing the Analysis Services Deployment Wizard..
        /// </summary>
        internal static string ExportBuildSuccess {
            get {
                return ResourceManager.GetString("ExportBuildSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build files successfully exported.
        /// </summary>
        internal static string ExportBuildSuccessCaption {
            get {
                return ResourceManager.GetString("ExportBuildSuccessCaption", resourceCulture);
            }
        }
    }
}
